version: "3"

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 127.0.0.1:6379:6379 #expose redis to connections from localhost only
    #command: 
    volumes: 
      - redis:/data

  app:
    build:
      context: ./
      args:
          ZIMVERSION: 3.1.0
    container_name: app
    network_mode: "host" #Such that swarm-cli can connect to the bee node running on localhost
    volumes:
      - "./src:/app/src"
      - "./data:/app/data"
      - "./test:/app/test"
    depends_on:
      - redis

volumes:
  redis:
